In [23]:
"""
We're are going to create a motion_detector which detects moving objects and highlights it in a rectangle
in real time through our camera.
For, it to work more accurately our first frame should be a static background frame
We'll also record the time when a moving object comes into the frame and goes out of it...

We'll store the timings in a pandas dataframe
"""
import cv2
from datetime import datetime as dt
import pandas as pd

# Storing the first frame of the video i.e a numpy array in a variable, we prefer the frame to be static
first_frame = None # We'll store it later in the while loop

status_list = [None, None] # Consist of 0 and 1, 0 represents no object present and 1 represents object present
# None is added just to prevent the IndexError
time_list = []
# Dataframe initialization
df = pd.DataFrame(columns = ['Entry', 'Exit'])

video = cv2.VideoCapture(0)

while True:
    # the loop helps us to display a series of frames as captured by the camera.
    check, frame  = video.read()

    status = 0 #First frame is considered to be static and hence 0
    # We'll use status to update status_list for each frame

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # we can also display the gray image

    gray = cv2.GaussianBlur(gray, (21, 21), 0)
    """We blur the image so as to smooth it as it removes the noise and thus increasing the
    accuracy in calculation of the diffrence between the images.
    2nd parameter is the width and the height of the Gaussian Kernel which is +ve and odd,
    basically the parameters of blurness.
    the last parameter 0 is the Standard Deviation"""


    if first_frame is None:
        first_frame = gray
        continue  # When the first frame is captured we don't want to execute the rest of the code for this frame


    """Now we can apply the delta frame, that means we can calculate the difference
    between the first frame and the current frame"""

    delta_frame = cv2.absdiff(first_frame, gray)

    """Now applying threshold and obtaining its frame.
    30 (thresh)-> the threshold value for each array element of the delta_frame
    255 (maxval)-> the color we want to impart it to display in the frame when it crosses the threshold,
    It is the maximum value to use with the THRESH_BINARY and THRESH_BINARY_INV thresholding types.
    THRESH_BINARY -> it's a function which checks for thresh value and equates it maxval on crossing it
    otherwise 0.""
    cv2.threshold returns a tuple in which the first item is the thresh
    and the second item is the required frame and hence [1].
    The first item is required for other methods which are used other than THRESH_BINARY"""

    thresh_frame = cv2.threshold(delta_frame, 30, 255, cv2.THRESH_BINARY)[1]


    """Now to smooth the white area of threshold frame we use cv2.dilate()
    The first parameter is the original image,kernel is the matrix with which image is
    convolved and third parameter is the number of iterations,
    which will determine how much you want to dilate a given image."""

    thresh_frame = cv2.dilate(thresh_frame, None, iterations = 2)

    """Now we'll detect contours, for that we've two two methods
    - find contours method -> here we'll find them and store them in a tuple,
      finding contours is like finding white object from black background
    - draw contours method -> here we'll draw them"""

    cnts, heirarchy = cv2.findContours(thresh_frame.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

    # We'll filter out the contours Now
    for contour in cnts:
        if cv2.contourArea(contour) < 3000: # Adjust the pixel accordingly to what you wanna capture
            continue
        # Now drawing the rectangle

        status = 1 # we've found a moving

        (x, y, w, h) = cv2.boundingRect(contour)
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,0), 2)

    # Here we append the status of each frame to the status_list

    status_list.append(status)

    # We lose a lot of memory in status_list as it consists of status of each and every frame
    # We require on;y the last two status' for checking
    status_list = status_list[-2: ]  # We do this for the sake of improvement in memory saving

    # If we want the status_list to be preserved we can create a copy of it or save it to another
    # list before this step

    # Now we need to note time when an object either enters or exit the frame
    if status_list[-1]==1  and  status_list[-2]==0:
        time_list.append(dt.now())
    if status_list[-1]==0  and  status_list[-2]==1:
        time_list.append(dt.now())


    cv2.imshow("Gray Frame", gray)
    cv2.imshow("Delta Frame", delta_frame)
    cv2.imshow("Threshold Frame", thresh_frame)
    cv2.imshow("Color Frame", frame)

    key = cv2.waitKey(1)

    # print(gray)
    # print(delta_frame)

    if key == ord('q'):  # q for quit...lol
        if status == 1:
            time_list.append(dt.now()) #When the object has not exited the frame before pressing 'q',
            # then that time is the exit time for the object
        break

# print(status_list)
# print(time_list)

# Now appending the DataFrame, remember the pandas append is not inplace
for i in range(0, len(time_list), 2):
    #Taking 2 steps at a time
    df = df.append({"Entry": time_list[i], "Exit" : time_list[i+1]},
                    ignore_index = True)

# print(df)
df.to_csv("Times.csv")
"""We'll use this file to plot a time graph for the object , where we display the entry and exit time
of the object in our frame...
The code for this plot is written in time_plotting.py"""


video.release()  # releases the camera...

cv2.destroyAllWindows()

In [24]:
from bokeh.plotting import figure, show, output_file
from datetime import datetime as dt
from bokeh.models import HoverTool, ColumnDataSource

# We'll do some formatting in our df for displaying it on hover
df['Entry_string'] = df['Entry'].dt.strftime("%Y-%m-%d  %H:%M:%S")
df['Exit_string'] = df['Exit'].dt.strftime("%Y-%m-%d  %H:%M:%S")

cds = ColumnDataSource(df)

p = figure(x_axis_type = 'datetime', height = 300 ,sizing_mode = "scale_width", title = "Motion Graph")

p.yaxis.minor_tick_line_color = None
p.ygrid[0].ticker.desired_num_ticks = 1

"""
desired_num_ticksÂ¶

    property type: Int

    A desired target number of major tick positions to generate across the plot range.
"""

hover = HoverTool(tooltips = [("Entry ", "@Entry_string"), ("Exit ", "@Exit_string")])
p.add_tools(hover)

q = p.quad(source = cds,left = "Entry",right = "Exit",bottom=0,top = 1, color = "green")

output_file("motion_graph.html")

show(p)

In [25]:
df.Entry_string.dtype

dtype('O')

In [26]:
df.Entry.dtype

dtype('<M8[ns]')

In [5]:
from pandas_datareader import data
# from datetime import datetime as dt
import datetime
from bokeh.plotting import figure, show, output_file 

start = datetime.datetime(2016,3,1)
end = datetime.datetime(2016,3,10)

df = data.DataReader(name='GOOG', data_source='iex', start = start, end=end)

In [8]:
df.index.dtype

dtype('O')

In [11]:
df

              open      high     low   close   volume
date
2016-03-01  703.62  718.8100  699.77  718.81  2151419
2016-03-02  719.00  720.0000  712.00  718.85  1629003
2016-03-03  718.68  719.4500  706.02  712.42  1957974
2016-03-04  714.99  716.4900  706.02  710.89  1972077
2016-03-07  706.90  708.0912  686.90  695.16  2988026
2016-03-08  688.59  703.7900  685.34  693.97  2076331
2016-03-09  698.47  705.6800  694.00  705.24  1421515
2016-03-10  708.12  716.4400  703.36  712.82  2833525

In [12]:
df['Date'] = df.index

In [13]:
df

              open      high     low   close   volume        Date
date
2016-03-01  703.62  718.8100  699.77  718.81  2151419  2016-03-01
2016-03-02  719.00  720.0000  712.00  718.85  1629003  2016-03-02
2016-03-03  718.68  719.4500  706.02  712.42  1957974  2016-03-03
2016-03-04  714.99  716.4900  706.02  710.89  1972077  2016-03-04
2016-03-07  706.90  708.0912  686.90  695.16  2988026  2016-03-07
2016-03-08  688.59  703.7900  685.34  693.97  2076331  2016-03-08
2016-03-09  698.47  705.6800  694.00  705.24  1421515  2016-03-09
2016-03-10  708.12  716.4400  703.36  712.82  2833525  2016-03-10

In [15]:
df.dtypes

open      float64
high      float64
low       float64
close     float64
volume      int64
Date       object
dtype: object

In [16]:
import pandas as pd
df['Date'] = pd.to_datetime(df.Date)
df.Date.dt.strftime("%Y-%m-%d")

date
2016-03-01    2016-03-01
2016-03-02    2016-03-02
2016-03-03    2016-03-03
2016-03-04    2016-03-04
2016-03-07    2016-03-07
2016-03-08    2016-03-08
2016-03-09    2016-03-09
2016-03-10    2016-03-10
Name: Date, dtype: object

In [18]:
df.Date[df.Status == 'Increase'].dt.strftime("%Y-%m-%d")

AttributeError: 'DataFrame' object has no attribute 'Status'

In [20]:
def inc_or_dec(c, o):
    if c > o:
        status = 'Increase'
    elif c < o:
        status = 'Decrease'
    else:
        status = 'Equal'
    return status

df["Status"] = [inc_or_dec(c,o) for c,o in zip(df.close, df.open)]

In [21]:
df

              open      high     low   close   volume       Date    Status
date
2016-03-01  703.62  718.8100  699.77  718.81  2151419 2016-03-01  Increase
2016-03-02  719.00  720.0000  712.00  718.85  1629003 2016-03-02  Decrease
2016-03-03  718.68  719.4500  706.02  712.42  1957974 2016-03-03  Decrease
2016-03-04  714.99  716.4900  706.02  710.89  1972077 2016-03-04  Decrease
2016-03-07  706.90  708.0912  686.90  695.16  2988026 2016-03-07  Decrease
2016-03-08  688.59  703.7900  685.34  693.97  2076331 2016-03-08  Increase
2016-03-09  698.47  705.6800  694.00  705.24  1421515 2016-03-09  Increase
2016-03-10  708.12  716.4400  703.36  712.82  2833525 2016-03-10  Increase

In [22]:
df.Date[df.Status == 'Increase'].dt.strftime("%Y-%m-%d")

date
2016-03-01    2016-03-01
2016-03-08    2016-03-08
2016-03-09    2016-03-09
2016-03-10    2016-03-10
Name: Date, dtype: object

In [28]:
from pandas_datareader import data
from datetime import datetime as dt
from bokeh.plotting import figure, output_file, show
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.embed import components
from bokeh.resources import CDN
import pandas as pd

start = dt(2018,4,1)
end = dt(2018,4,30)
df_amazon = data.DataReader(name = 'AMZN', data_source='iex', start=start, end=end)

df_amazon.index = pd.to_datetime(df_amazon.index)

def inc_or_dec(c, o):
    if c > o:
        status = 'Increase'
    elif c < o:
        status = 'Decrease'
    else:
        status = 'Equal'
    return status

df_amazon["Status"] = [inc_or_dec(c,o) for c,o in zip(df_amazon.close, df_amazon.open)]
df_amazon['Middle'] = (df_amazon.open + df_amazon.close) / 2
df_amazon['Rect_Height'] = abs(df_amazon.open - df_amazon.close)

df_amazon['Date'] = df_amazon.index


# print(df_amazon.Date.dtype)
df_amazon['Date'] = pd.to_datetime(df_amazon.Date)
# df.Date.dt.strftime("%Y-%m-%d")

x_index_i = df_amazon.index[df_amazon.Status == 'Increase']
y_mids_i = df_amazon.Middle[df_amazon.Status =='Increase']
height_i = df_amazon.Rect_Height[df_amazon.Status == 'Increase']
d_i = df_amazon.Date[df_amazon.Status == 'Increase'].dt.strftime("%Y-%m-%d")

cds1=ColumnDataSource(data=dict(x = x_index_i,
                               y = y_mids_i,
                               span = height_i,
                               open=df_amazon.open[df_amazon.Status == 'Increase'],
                               close=df_amazon.close[df_amazon.Status == 'Increase'],
                               high=df_amazon.high[df_amazon.Status == 'Increase'],
                               low=df_amazon.low[df_amazon.Status == 'Increase'],
                               volume=df_amazon.volume[df_amazon.Status == 'Increase'],
                               date = d_i))

x_index_d = df_amazon.index[df_amazon.Status == 'Decrease']
y_mids_d = df_amazon.Middle[df_amazon.Status =='Decrease']
height_d = df_amazon.Rect_Height[df_amazon.Status == 'Decrease']
d_d = df_amazon.Date[df_amazon.Status == 'Decrease'].dt.strftime("%Y-%m-%d")
                                    
cds2=ColumnDataSource(data=dict(x = x_index_d,
                               y = y_mids_d,
                               span = height_d,
                               open=df_amazon.open[df_amazon.Status == 'Decrease'],
                               close=df_amazon.close[df_amazon.Status == 'Decrease'],
                               high=df_amazon.high[df_amazon.Status == 'Decrease'],
                               low=df_amazon.low[df_amazon.Status == 'Decrease'],
                               volume=df_amazon.volume[df_amazon.Status == 'Decrease'],
                               date = d_d))

p = figure(x_axis_type = 'datetime', height = 300,sizing_mode = 'scale_width')
p.title.text = "Candlestick Chart for Amazon"
p.grid.grid_line_alpha = 1
p.background_fill_color="#f5f5f5"
p.grid.grid_line_color="#7FFFD4"
p.xaxis.axis_label = 'Date'
p.yaxis.axis_label = 'Price'

hours_12 = 12*60*60*1000 # for width if rect



# p.segment(df_amazon.index,df_amazon.high, df_amazon.index, df_amazon.low, color = "black")
p.segment('x', 'high', 'x', 'low',color = "black", source = cds1)
p.segment('x', 'high', 'x', 'low',color = "black", source = cds2)

p.rect('x',
       'y',
       hours_12,
       'span',
       fill_color = "#98FB98",
       line_color = "black",
       source = cds1)

p.rect('x',
       'y',
       hours_12,
       'span',
       fill_color = "#FF6347",
       line_color = "black", source = cds2)


# df_amazon['Date_string'] = df_amazon.Date.dt.strftime("%Y-%m-%d %H:%M:%S")

hover = p.select(dict(type=HoverTool))
hover = HoverTool(tooltips = [("Open","@open{1.11}"),("Close", "@close{1.11}"),
                              ("High", "@high{1.11}"),("low", "@low{1.11}"),("date", "@Date")])
p.add_tools(hover)



# Now to embed it to a website

script, div = components(p)
cdn_js = CDN.js_files[0]
cdn_css = CDN.css_files[0]

output_file("Candlestick Chart for Amazon.html")
show(p)